spring.application.name=livetreamservice
server.port=8086

# Database Configuration - Separate database for Livestream Service
spring.datasource.url=jdbc:mysql://localhost:3306/livestreamdb?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# LiveKit Configuration
livekit.url=wss://livetream-7f2wlo6u.livekit.cloud
livekit.api-key=APIroUAKf3K9soB
livekit.api-secret=6RscGpoNsTqpXzaixecf1IDU0y2eYt7fdeR1GVmuOFvA
