spring.application.name=apigateway
server.port=8080

# Route to UserService
spring.cloud.gateway.server.webmvc.routes[0].id=userservice-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

# Route to UserService - Profile, Update, etc.
spring.cloud.gateway.server.webmvc.routes[6].id=userservice-profile
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/users/**

# Route to LivestreamService
spring.cloud.gateway.server.webmvc.routes[1].id=livestreamservice
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/livestream/**


# Route to ChatbotService
spring.cloud.gateway.server.webmvc.routes[2].id=chatbotservice
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/chat/**

# Route to ProductService
spring.cloud.gateway.server.webmvc.routes[3].id=productservice
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8089
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/products/**

# Route to ProductService - Products
spring.cloud.gateway.server.webmvc.routes[4].id=productservice-products
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/products/**

# Route to ProductService - Categories
spring.cloud.gateway.server.webmvc.routes[3].id=productservice-categories
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/categories/**

# Route to OrderService - Ratings
spring.cloud.gateway.server.webmvc.routes[4].id=orderservice-ratings
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/ratings/**

# Route to OrderService - Orders
spring.cloud.gateway.server.webmvc.routes[5].id=orderservice-orders
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/orders/**
