# ==========================================================
# MySQL ExternalName Service
# Trỏ về MySQL XAMPP chạy trên host machine
# ==========================================================
apiVersion: v1
kind: Service
metadata:
  name: mysql-host
  namespace: anvi-dev
spec:
  type: ExternalName
  externalName: host.docker.internal
