apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
  namespace: anvi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - name: productservice
        image: anvi/productservice:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/productdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8&useUnicode=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "anvi@root2025"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: STORE_SERVICE_URL
          value: "http://storeservice:8090"
        ports:
        - containerPort: 8087
        readinessProbe:
          tcpSocket:
            port: 8087
          initialDelaySeconds: 40
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: anvi
spec:
  selector:
    app: productservice
  ports:
  - port: 8087
    targetPort: 8087



